get http://localhost:3000/users

###
get http://localhost:3000/users/1

###
get http://localhost:3000/getAllPejantan

###
get http://localhost:3000/getAllObat

###
get http://localhost:3000/getAllPetugas

###
POST  http://localhost:3000
