get http://localhost:3000/api/user

###
get http://localhost:3000/users/1

###
get http://localhost:3000/api/pejantan

###
get http://localhost:3000/getAllObat

###
get http://localhost:3000/getAllPetugas

###
POST  http://localhost:3000
