get http://localhost:3000/getAllDataSapi

###
get http://localhost:3000/getAllUserData

###
get http://localhost:3000/getAllPejantan

###
get http://localhost:3000/getAllObat

###
get http://localhost:3000/getAllPetugas
